# Generated by Django 5.1.1 on 2024-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturematerial',
            name='file',
            field=models.BinaryField(),
        ),
    ]
