# Generated by Django 5.1.1 on 2024-09-06 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lecturematerial_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerial',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
