# Generated by Django 5.1.1 on 2024-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lecturematerial_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturematerial',
            name='file',
            field=models.FileField(upload_to='lectures/'),
        ),
    ]
